CREATE TABLE CUSTOMER (
	CUSTOMER_ID INT IDENTITY(1,1) PRIMARY KEY,
	CUSTOMER_NAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	VENDOR_PASSWORD VARCHAR(100) NOT NULL,
	PHONE_NUMBER BIGINT NOT NULL,
	CUSTOMER_ADDRESS TEXT,
	REGISTRATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VENDOR (
	VENDOR_ID INT IDENTITY(1,1) PRIMARY KEY,
	VENDOR_NAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	VENDOR_PASSWORD VARCHAR(100) NOT NULL,
	PHONE_NUMBER BIGINT NOT NULL,
	VENDOR_ADDRESS TEXT,
	REGISTRATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ORDER_TABLE (
	ORDER_ID INT IDENTITY(1,1) PRIMARY KEY,
	VENDOR_ID INT NOT NULL FOREIGN KEY REFERENCES VENDOR(VENDOR_ID),
	CUSTOMER_ID INT NOT NULL FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID),
	TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
	ORDER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	ORDER_STATUS VARCHAR(20) NOT NULL CHECK (ORDER_STATUS IN ('Pending', 'Completed', 'Cancelled'))
);

CREATE TABLE MENU (
	ITEM_ID INT IDENTITY(1,1) PRIMARY KEY,
	VENDOR_ID INT NOT NULL FOREIGN KEY REFERENCES VENDOR(VENDOR_ID),
	ITEM_NAME VARCHAR(25),
	ITEM_DESCRIPTION TEXT,
	ITEM_PRICE DECIMAL(10,2) NOT NULL,
	CATEGORY VARCHAR(25),
	ITEM_AVAILABILITY BIT DEFAULT 0,
	DIET_TYPE VARCHAR(25) CHECK (DIET_TYPE IN ('Veg', 'Non Veg', 'Healthy', 'Sugar Free', 'Gluten Free')),
	HAS_OFFER BIT DEFAULT 0,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ORDER_ITEMS (
	ORDER_ITEM_ID INT IDENTITY(1,1) PRIMARY KEY,
	ORDER_ID INT NOT NULL FOREIGN KEY REFERENCES ORDER_TABLE(ORDER_ID),
	ITEM_ID INT NOT NULL FOREIGN KEY REFERENCES MENU(ITEM_ID),
	QUANTITY INT NOT NULL,
	ITEM_PRICE DECIMAL(10,2) NOT NULL,
	HAS_OFFER BIT DEFAULT 0
);

CREATE TABLE CUSTOMER_REVIEWS (
	REVIEW_ID INT IDENTITY(1,1) PRIMARY KEY,
	CUSTOMER_ID INT NOT NULL FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID),
	VENDOR_ID INT NOT NULL FOREIGN KEY REFERENCES VENDOR(VENDOR_ID),
	RATING DECIMAL(3,2) CHECK (RATING BETWEEN 0 AND 5),
	COMMENTS TEXT,
	REVIEW_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ORDER_STATUS_TABLE (
	STATUS_ID INT IDENTITY(1,1) PRIMARY KEY,
	ORDER_ID INT NOT NULL FOREIGN KEY REFERENCES ORDER_TABLE(ORDER_ID),
	ORDER_STATUS VARCHAR(25),
	STATUS_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SPECIAL_OFFER (
	OFFER_ID INT IDENTITY(1,1) PRIMARY KEY,
	VENDOR_ID INT NOT NULL FOREIGN KEY REFERENCES VENDOR(VENDOR_ID),
	ITEM_ID INT NOT NULL FOREIGN KEY REFERENCES MENU(ITEM_ID),
	OFFER_TYPE VARCHAR(25),
	OFFER_DESCRIPTION TEXT,
	OFFER_START_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	OFFER_END_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	DISCOUNT_PERCENTAGE DECIMAL(10,2),
	IS_ACTIVE BIT DEFAULT 0
);

SELECT * FROM VENDOR